### ISSUE TITLE
Keyboard ALT-Key

### ISSUE THREAD

**Issue by AVRsteffen** [Zigazou/myterminal#4]
Hello Frédéric, I see you have been hardworking and added a keyboard interface. I am about to test it. I noticed that an ALT key pressed once is always "TRUE" and does not change back to the "FALSE" state.
I don't think that should be the case.
If not, I made an addition to the file "ps2_keyboard_state.v" to fix the problem.

`task state_break;
	begin
		state <= STATE_IDLE;
		case (scan_code_in)
			SCAN_SHIFT_LEFT: keyboard_shift_left <= FALSE;
			SCAN_SHIFT_RIGHT: keyboard_shift_right <= FALSE;
			SCAN_CTRL_LEFT: keyboard_ctrl_left <= FALSE;
			SCAN_ALT: keyboard_alt <= FALSE;    // <--------------- Here I did added
		endcase
	end
endtask`

I hope it is right.

In addition, I am trying to find a solution for using different keyboards (FR / EN / DE).

**Comment by Zigazou** [comment]
Hi !
This has been included, thanks !
